import React from 'react'

export const TermsOfService = () => {
    return (
        <>
          <span id="service" className="title">Terms of Service</span>
                        <p className="description">This end user agreement (the "Agreement") should be read by you (the "User" or "you") in its entirety prior to your use of Spherium's service or products. Be aware that this Agreement constitutes a legally binding agreement between you and Spherium (referred to herein as "we"), a company owning and operating the website www.spherium.finance and the services provided accordingly (the "Service").</p>
                        
                        <p className="subtittle">1. Grant of License</p>
                        
                        <p className="description">● We grant the User a non-exclusive, personal, non-transferable right to use the Service on his personal computer or other device that accesses the Internet in order to access and use the services available and described on the website subject to the terms and conditions contained herein.<br/><br/>
                        ●	The Service is not for use by (i) minors and individuals under the age of 18 years, (ii) individuals who can be considered minors or under the age of majority adulthood in their specific jurisdiction(s) (iii) individuals accessing or using the Service from any jurisdiction in which it is illegal to do so. Spherium does not have the ability to verify the legality of the Service in every jurisdiction, therefore it is entirely up to the User to determine whether or not their use of the Service is lawful.<br/><br/> 
                        ●	Spherium is the sole holder of all rights in and to the Service and code, technology, organization and structure, architecture, including copyright, trade secrets, intellectual property and other rights. You may not: (i) copy, create derivative works, distribute, publish, reverse engineer, decompile, disassemble, modify, or translate the website or the Service; or (ii) use the Service that in any way is prohibited by applicable laws or regulations (each of the above herein defined as an "Unauthorized Use").<br/><br/> 
                        ●	Spherium reserves any and all rights implied or otherwise, which are not expressly granted to the User hereunder and retain all rights, title and interest in and to the Service. You agree that you will be solely liable for any damage, costs or expenses arising out of or in connection with the commission by you of any Unauthorized Use. You shall notify us immediately upon becoming aware of the commission by any person of any Unauthorized Use and provide all reasonable assistance with any investigations it conducts in light of the information provided by you in this respect.<br/><br/>
                        ●	The term "Spherium", the domain names and any other trademarks or service marks used as part of the Service (the "Trademarks"), are solely owned by Spherium Pte. Ltd. In addition, all content on the website, including, but not limited to, the images, pictures, graphics, photographs, animations, videos, music, audio and text (the "Site Content") belongs to us and is protected by copyright and/or other intellectual property or other rights. You hereby acknowledge that by using the Service, you obtain no rights in the Site Content and/or the Trademarks, or any part thereof. Under no circumstances may you use the Site Content and/or the Trademarks without our prior written consent. Additionally, you agree not to do anything that will harm or potentially harm the rights, including the intellectual property rights of Spherium.
                       </p>
                       <p className="subtittle">2. No Warranties/Final Decisions</p>
                       <p className="description">●	Spherium disclaims any and all warranties, expressed or implied, in connection with the service which is provided to you "as is" and we provide you with no warranty or representation whatsoever regarding its quality, fitness for purpose, completeness or accuracy.<br/><br/>
                       ●	Regardless thereof, we provide no warranty that the service will be uninterrupted, timely or error-free, or that defects will be corrected.<br/><br/>
                       ●	You agree to the rules of the Service provided and described on the website as well as with Spherium retaining all authority over the issuing, maintenance, and closing of the Service. The decisions of the management, concerning any use of the Service, or dispute resolution, is final and shall not be open to review or appeal.
                       </p>
                       <p className="subtittle">3. Representations and Warranties</p>
                       <p className="description">Prior to your use of the Service and on an ongoing basis you represent, warrant, covenant and agree that<br/><br/>
                       ●	you are (i) aged 18 or over, (ii) you are of the age of majority in your jurisdiction, (iii) you are accessing the Service from a jurisdiction in which it is legal to do so, (iv) you are not a Politically Exposed Person (PEP) nor are you on any U.S. or EU Sanctions lists or terrorism finance watchlists, and (v) that you will inform us immediately if you enter onto one of these lists or change your residence to a prohibited jurisdiction;<br/><br/>
                       ●	your use of the Service is at your sole option, discretion and risk;
                       ●	you realize that cryptocurrency values can fluctuate greatly in value depending on market conditions and that you shall hold Spherium harmless for any loss or damages arising from such volatility;<br/><br/>
                       ●	you are solely responsible for any applicable taxes which may be payable on cryptocurrency traded or transacted by you through your using the Service;<br/><br/>
                       ●	the telecommunications networks, blockchain networks (such as Polkadot and Ethereum) and Internet access services required for you to access and use the Service are entirely beyond the control of Spherium and we shall have no liability whatsoever for any outages, slowness, capacity constraints or other deficiencies affecting the same;<br/><br/> 
                       ●	should you discover a bug or error that may lead to an exploit of the Service or other loss of funds, you shall notify us in a timely manner. Furthermore, any attempt by you to use such a discovered exploit or bug for illicit financial gain is illegal and strictly prohibited under this Agreement;
                       ●	Spherium reserves the right to prosecute to the fullest extent of the law anyone who exploits or attempts to exploit the Service in an unlawful manner.
                      </p>
                      <p className="subtittle">4. Proper Use</p>
                      <p className="description">●	PERSONAL USE. The Service is intended solely for the User’s personal use. The User is only allowed to use the Service for personal use, and may not create multiple accounts, including for the purpose of collusion and/or abuse of service.<br/><br/>
                      ●	EXPLOITS & BUGS. The Service is provided as is, and any exploitation of the Service or errors in program logic and/or code (bugs) constitutes a Prohibited Use and a material breach of this Agreement. Any funds the user may misappropriate in this manner pursuant to this clause shall be considered void and the immediate property of Spherium without limit.<br/><br/> 
                      ●	JURISDICTIONS. Persons located in or residents of the United States, North Korea, Iran, Venezuela, Yemen, Syria or any other jurisdiction in which it is prohibited to use the types of services of the same kind as the Service provided by Spherium (the ”Prohibited Jurisdictions”) are not permitted to make use of the Service. For the avoidance of doubt, the foregoing restrictions on Service from Prohibited Jurisdictions apply equally to residents and citizens of other nations while located in a Prohibited Jurisdiction. Any attempt to circumvent the restrictions on usage by any persons located in a Prohibited Jurisdiction or Restricted Jurisdiction, is a breach of this Agreement.<br/><br/>  
                      ●	Any and all monies (including cryptocurrencies) of a person located in a Prohibited Jurisdiction on the Service are VOID and can be confiscated or may be returned to the person at Spherium's sole discretion.<br/><br/>
                      ●	Spherium is a permissionless and fully decentralized platform for token sales, swaps as well as lending and borrowing of assets. We expressly prohibit and reject the use of the Service for any form of illicit activity, including money laundering, terrorist financing or trade sanctions violations, consistent with various jurisdictions’ laws, regulations and norms.<br/><br/>  
                      ●	Although we make no warranty as to the merit, legality or juridical nature of any token (including whether or not it is considered a security or financial instrument under any applicable Securities Laws), we nonetheless understand the need of some token projects to require KYC/AML on their token sale participants. The use of KYC/AML tools on Spherium by entities using the Service is completely at the discretion of said entities. Therefore, and at the sole behest of fundraising entities and/or competent regulatory authorities, Spherium reserves the right, at any time, to ask for any KYC documentation it deems necessary to determine the identity and location of a User as well as to restrict service and payment until identity is sufficiently determined. Spherium further reserves the right to share submitted KYC information and documentation to 3rd parties to verify the authenticity of submitted information, and the end user (you) agree to this by using the Service.<br/><br/> 
                      ●	Spherium also reserves the right to confiscate any and all funds that are found to be in violation of relevant and applicable anti-money laundering (AML) and countering terrorism financing (CFT) laws and regulations, and to cooperate with the competent authorities when and if necessary. 
                     </p>
                     <p className="subtittle">5. Consequences of Breach of Terms of Service</p>
                     <p className="description">● Without prejudice to any other rights, if a User breaches in whole or in part any provision contained herein, Spherium reserves the right to take such action as it sees fit, including terminating this Agreement or any other agreement in place with the User and/or taking legal action against such User.<br/><br/>
                     ●	You agree to fully indemnify, defend and hold harmless Spherium and its shareholders, directors, agents and employees from and against all claims, demands, liabilities, damages, losses, costs and expenses, including legal fees and any other charges whatsoever, howsoever caused, that may arise as a result of: (i) your breach of this Agreement, in whole or in part; (ii) violation by you of any law or any third party rights; and (iii) use by you of the Service.<br/><br/>
                     ●	Under no circumstances, including negligence, shall we be liable for any special, incidental, direct, indirect or consequential damages whatsoever (including, without limitation, damages for loss of business profits, business interruption, loss of business information, or any other pecuniary loss) arising out of the use (or misuse) of the Service even if Spherium had prior knowledge of the possibility of such damages.
                     </p>
                     <p className="subtittle">6. Disputes</p>
                     <p className="description">If a User wishes to make a complaint, please contact our customer service team at info@spherium.finance. Should any dispute not be resolved to your satisfaction you may pursue remedies in the governing law jurisdiction set forth below.</p>    
                     <p className="subtittle">7. Governing Law</p>
                     <p className="description">The Agreement and any matters relating hereto shall be governed by, and construed in accordance with, the laws of Singapore. You irrevocably agree that, subject as provided below, the courts of Singapore shall have exclusive jurisdiction in relation to any claim, dispute or difference concerning the Agreement and any matter arising therefrom and irrevocably waive any right that it may have to object to an action being brought in those courts, or to claim that the action has been brought in an inconvenient forum, or that those courts do not have jurisdiction. Nothing in this clause shall limit the right of Spherium to take proceedings against you in any other court of competent jurisdiction nor shall the taking of proceedings in any one or more jurisdictions preclude the taking of proceedings in any other jurisdictions, whether concurrently or not, to the extent permitted by the law of such other jurisdiction.</p>    
                     <p className="subtittle">8. Miscellaneous</p>
                     <p className="description">●	We reserve the right to update or modify this Agreement or any part thereof at any time or otherwise change the Service without notice and you will be bound by such amended Agreement upon posting. Therefore, we encourage you to check the terms and conditions contained in the version of the Agreement in force at such time. Your continued use of the Service shall be deemed to attest to your agreement to any amendments to the Agreement;<br/><br/>
                     ●	If a provision of this Agreement is or becomes illegal, invalid or unenforceable in any jurisdiction, that shall not affect the validity or enforceability in that jurisdiction of any other provision hereof or the validity or enforceability in other jurisdictions of that or any other provision hereof;<br/><br/>
                     ●	Spherium reserves the right to assign this agreement, in whole or in part, at any time without notice. The User may not assign any of his/her rights or obligations under this Agreement;<br/><br/>
                     ●	No waiver of any breach of any provision of this Agreement (including the failure to require strict and literal performance of or compliance with any provision of this Agreement) shall in any way be construed as a waiver of any subsequent breach of such provision or of any breach of any other provision of this Agreement;<br/><br/>
                     ●	Nothing in this Agreement shall create or confer any rights or other benefits in favor of any third parties not party to this Agreement;<br/><br/>
                     ●	Nothing in this Agreement shall create or be deemed to create a partnership, agency, trust arrangement, fiduciary relationship or joint venture between you and Spherium;<br/><br/>
                     ●	This Agreement constitutes the entire understanding and agreement between you and Spherium regarding the Service and supersedes any prior agreement, understanding, or arrangement between you and Spherium.
                    </p>    
        </>
    )
}
